class AppStrings {
  // --- Core Configuration ---
  static const String appName = 'Paykari Bazar';
  static const String defaultFontFamily = 'GoogleFonts.poppins';

  // --- API & Storage Paths ---
  static const String clipDropApiUrl = 'https://clipdrop-api.co/remove-background/v1';
  static const String transparentProductsPath = 'transparent_products';

  // --- Localization Engine ---
  static String get(String key, String lang, {Map<String, dynamic>? remoteTranslations}) {
    if (remoteTranslations != null && remoteTranslations.containsKey(key)) {
      final data = remoteTranslations[key];
      if (data is Map && data['isHidden'] != true) {
        return (data[lang] ?? _english[key] ?? _bangla[key] ?? key).toString();
      }
    }

    final bool isBn = lang == 'bn';
    final Map<String, String> translations = isBn ? _bangla : _english;
    return translations[key] ?? key;
  }

  // --- Initial Data for Database Seeding ---
  static Map<String, Map<String, dynamic>> get initialData {
    final Map<String, Map<String, dynamic>> data = {};
    _english.forEach((key, value) {
      data[key] = {
        'en': value,
        'bn': _bangla[key] ?? value,
        'isConfirmed': true,
        'isHidden': false,
      };
    });
    return data;
  }

  // --- Bangla Translations ---
  static const Map<String, String> _bangla = {
    'appName': 'পাইকারী বাজার',
    'appNameAdmin': 'পাইকারী বাজার (অ্যাডমিন)',
    'rewardsRankings': 'রিওয়ার্ড ও র‍্যাঙ্কিং',
    'voucherCenter': 'কুপন ও ভাউচার',
    'topBuyersMonth': 'সেরা ক্রেতা (এই মাস)',
    'topBuyersPerformance': 'সেরা ক্রেতাদের পারফরম্যান্স',
    'emergencyHeroesMonth': 'মেডিসিন বীর (এই মাস)',
    'bloodHeroesMonth': 'ব্লাড দিয়ে সহায়তাকারী হিরো (এই মাস)',
    'prevMonthWinners': 'গত মাসের বিজয়ীরা',
    'megaDrawWinners': 'মেগা ড্র বিজয়ীরা',
    'availableCoupons': 'চলতি কুপনসমূহ',
    'emergencyMedicineBlood': 'জরুরি ঔষধ ও রক্ত',
    'riderDashboard': 'রাইডার ড্যাশবোর্ড',
    'downloadHistory': 'অর্ডার হিস্ট্রি ডাউনলোড',
    'helpSupport': 'হেল্প ও সাপোর্ট',
    'joinPaykariBazar': 'পাইকারি বাজারে যোগ দিন',
    'account': 'অ্যাকাউন্ট',
    'pharmacy': 'ফার্মেসি',
    'bloodAid': 'রক্ত সহায়তা',
    'bloodRequest': 'রক্তের আবেদন',
    'helpline': 'হেল্পলাইন',
    'home': 'হোম',
    'offers': 'অফার',
    'rewards': 'রিওয়ার্ড',
    'profile': 'প্রোফাইল',
    'emergencyService': 'জরূরী সেবা',
    'noPurchasesMonth': 'এই মাসে এখনো কোনো কেনাকাটা হয়নি',
    'noActiveHeroes': 'এই মাসে কোনো বীর নেই',
    'noMegaDraws': 'কোনো মেগা ড্র এখনো হয়নি',
    'noVouchersFound': 'কোনো কুপন পাওয়া যায়নি',
    'noActiveCoupons': 'বর্তমানে কোনো কুপন নেই',
    'cartEmpty': 'আপনার কার্ট খালি',
    'noTasks': 'কোনো কাজ নেই',
    'noProductsFound': 'কোনো পণ্য পাওয়া যায়নি',
    'noFavouritesYet': 'পছন্দের তালিকায় কিছু নেই',
    'exitAppTitle': 'অ্যাপ থেকে বের হতে চান?',
    'exitAppContent': 'আপনি কি নিশ্চিত যে আপনি অ্যাপটি বন্ধ করতে চান?',
    'viewAll': 'সব দেখুন',
    'flashDeals': 'ফ্ল্যাশ ডিল',
    'newArrivals': 'নতুন পণ্য',
    'justForYou': 'আপনার জন্য বিশেষ',
    'comboPack': 'কম্বো প্যাক',
    'quickReorder': 'দ্রুত রি-অর্ডার',
    'buyLastItems': 'আপনার শেষ কেনা পণ্যগুলো আবার কিনুন',
    'reorderBtn': 'অর্ডার',
    'searchHint': 'পণ্য খুঁজুন...',
    'noFlashSales': 'বর্তমানে কোনো ফ্ল্যাশ সেল নেই',
    'loading': 'লোড হচ্ছে...',
    'pleaseWait': 'দয়া করে অপেক্ষা করুন',
    'adminDashboard': 'অ্যাডমিন ড্যাশবোর্ড',
    'businessOverview': 'ব্যবসার সংক্ষিপ্ত বিবরণ',
    'totalOrders': 'মোট অর্ডার',
    'totalUsers': 'মোট ইউজার',
    'revenue': 'মোট আয়',
    'pending': 'অপেক্ষমান',
    'orderTrends': 'অর্ডারের ধরণ',
    'topSellingProducts': 'সর্বাধিক বিক্রিত পণ্য',
    'salesByCategory': 'ক্যাটাগরি অনুযায়ী সেলস',
    'viewFeedbacks': 'ফিডব্যাক দেখুন',
    'alert': 'সতর্কবার্তা',
    'newMessage': 'নতুন বার্তা',
    'cartReminderTitle': 'আপনার কার্টে পণ্য রয়েছে!',
    'cartReminderBody': 'আপনার পছন্দের পণ্যগুলো হারিয়ে যাওয়ার আগেই অর্ডার সম্পন্ন করুন।',
    'emergencyOrderTitle': 'জরুরি অর্ডার!',
    'emergencyOrderBody': 'একটি জরুরি অর্ডার এসেছে। অনুগ্রহ করে দ্রুত ব্যবস্থা নিন।',
    'priceDropTitle': 'দাম কমেছে!',
    'priceDropBody': 'আপনার পছন্দের পণ্যের দাম এখন কম!',
    'deliveryProximityTitle': 'দেলিভারি রাইডার কাছেই!',
    'deliveryProximityBody': 'আপনার অর্ডারটি নিয়ে রাইডার কিছুক্ষণের মধ্যেই পৌঁছে যাবেন।',
    'bloodNeeded': 'রক্ত প্রয়োজন',
    'bloodNeededDesc': 'Groups এর রক্ত প্রয়োজন',
    'orderUpdateTitle': 'অর্ডার আপডেট',
    'order_label': 'অর্ডার',
    'order': 'অর্ডার',
    'Pending': 'অপেক্ষমান',
    'Processing': 'প্রসেসিং হচ্ছে',
    'Shipped': 'পাঠানো হয়েছে',
    'Delivered': 'দেলিভারি করা হয়েছে',
    'downloadInvoice': 'ইনভয়েস ডাউনলোড করুন',
    'deliveryTasks': 'দেলিভারি টাস্ক',
    'markAsDelivered': 'দেলিভারি সম্পন্ন',
    'callCustomer': 'কল করুন',
    'navigation': 'রাস্তা দেখুন',
    'noAssignedTasks': 'আপনার কোনো এসাইন করা টাস্ক নেই',
    'staffLogin': 'স্টাফ লগইন',
    'invalidStaff': 'এই অ্যাকাউন্টটি স্টাফ হিসেবে নিবন্ধিত নয়',
    'latestAdded': 'সর্বশেষ যুক্ত',
    'nameAz': 'নাম (A-Z)',
    'priceLowHigh': 'দাম: কম থেকে বেশি',
    'priceHighLow': 'দাম: বেশি থেকে কম',
    'priceRange': 'দামের সীমা',
    'feedbackTitle': 'আপনার মতামত জানান',
    'submitFeedback': 'মতামত পাঠান',
    'feedbackHint': 'এখানে লিখুন...',
    'thankYouFeedback': 'আপনার মতামতের জন্য ধন্যবাদ!',
    'ratingRequired': 'দয়া করে একটি রেটিং দিন',
    'errorOccurred': 'একটি সমস্যা হয়েছে',
    'networkError': 'ইন্টারনেট কানেকশন নেই। দয়া করে চেক করুন।',
    'serverError': 'সার্ভারে সমস্যা হচ্ছে। আবার চেষ্টা করুন।',
    'unauthorized': 'দয়া করে আবার লগইন করুন।',
    'userNotFound': 'এই ইমেইল বা নম্বর দিয়ে কোনো অ্যাকাউন্ট পাওয়া যায়নি',
    'wrongPassword': 'ভুল পাসওয়ার্ড। আবার চেষ্টা করুন।',
    'tooManyRequests': 'অতিরিক্ত চেষ্টার কারণে সাময়িকভাবে ব্লক করা হয়েছে। পরে চেষ্টা করুন।',
    'authError': 'লগইন করতে সমস্যা হচ্ছে',
    'tryAgain': 'আবার চেষ্টা করুন',
    'emailAlreadyInUse': 'এই ইমেইলটি ইতিপূর্বে ব্যবহার করা হয়েছে',
    'uploadFailed': 'আপলোড ব্যর্থ হয়েছে',
    'success': 'সফল হয়েছে!',
    'updateSuccess': 'সফলভাবে আপডেট করা হয়েছে',
    'fillAllFields': 'সবগুলো ঘর পূরণ করুন',
    'collectCoupons': 'অতিরিক্ত ছাড়ের জন্য কুপন সংগ্রহ করুন',
    'copyCode': 'কোড কপি হয়েছে!',
    'reorderFastTrack': 'দ্রুত আগের অর্ডার করুন',
    'submitOrder': 'অর্ডার সাবমিট করুন',
    'logout': 'লগআউট করুন',
    'login': 'লগইন',
    'signup': 'নিবন্ধন',
    'cancel': 'বাতিল',
    'yes': 'হ্যাঁ',
    'no': 'না',
    'viewCart': 'কার্ট দেখুন',
    'add': 'যোগ করুন',
    'buyNow': 'এখনই কিনুন: ',
    'startShopping': 'কেনাকাটা শুরু করুন',
    'confirmOrder': 'অর্ডার নিশ্চিত করুন',
    'saveChanges': 'পরিবর্তন সেভ করুন',
    'shareEarn': 'শেয়ার করে আয় করুন',
    'mobile': 'মোাবাইল',
    'email': 'ইমেইল',
    'rememberMe': 'মনে রাখুন',
    'forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'orContinueWith': 'অথবা চালিয়ে যান',
    'noAccount': 'অ্যাকাউন্ট নেই?',
    'myCurrentPoints': 'আমার বর্তমান পয়েন্ট',
    'redeemPointsHint': 'চেকআউট করার সময় ডিসকাউন্ট নিন',
    'pts': 'পয়েন্ট',
    'rewardEarned': 'পুরস্কার জিতেছেন! 🎁',
    'pointsEarnedMsg': 'পয়েন্ট অর্জিত হয়েছে!',
    'loginTitle': 'লগইন করুন',
    'signupTitle': 'নিবন্ধন করুন',
    'mobileNumber': 'মোবাইল নাম্বার',
    'password': 'পাসওয়ার্ড',
    'fullName': 'পুরো নাম',
    'emailAddress': 'ইমেইল এড্রেস',
    'referralCode': 'রেফার কোড (ঐচ্ছিক)',
    'profileProgress': 'প্রোফাইল অগ্রগতি',
    'editProfile': 'প্রোফাইল এডিট করুন',
    'changePassword': 'পাসword পরিবর্তন',
    'liveChat': 'লাইভ চ্যাট',
    'whatsappSupport': 'হোয়াটসঅ্যাপ সহায়তা',
    'directCall': 'সরাসরি কল করুন',
    'howToUse': 'কিভাবে ব্যবহার করবেন',
    'termsConditions': 'শর্তাবলী ও নিয়ম',
    'patientType': 'রোগীর ধরন',
    'bloodGroup': 'রক্তের গ্রুপ',
    'bagsNeeded': 'ব্যাগ সংখ্যা',
    'hospitalArea': 'হাসপাল অথবা এলাকা',
    'contactNumber': 'যোগাযোগের নম্বর',
    'bloodRequestAlert': 'জরুরি রক্তের অনুরোধ নিকটস্থ দাতাদের কাছে পাঠানো হবে।',
    'medicineDetails': 'ঔষধের বিবরণ / নির্দেশনা',
    'attachPrescription': 'প্রেসক্রিপশন আপলোড করুন',
    'medicineNamesHint': 'ঔষধের নাম ও পরিমাণ লিখুন...',
    'child': 'শিশু',
    'youth': 'যুবক-যুবতী',
    'elderly': 'বৃদ্ধ-বৃদ্ধা',
    'pregnantMother': 'গর্ভধারিণী মা',
    'seriouslyIll': 'গুরুতর অসুস্থ',
    'criticallyInjured': 'গুরুতর আহত',
    'applyForSupportTeam': 'সাপোর্ট টিমে আবেদন করুন',
    'orderPlacedSuccess': 'অর্ডার সফলভাবে সম্পন্ন হয়েছে',
    'titleMessageRequired': 'শিরোনাম এবং বার্তা প্রয়োজন',
    'locationAdded': 'লোকেশন যোগ করা হয়েছে',
    'noPendingDeviceRequests': 'কোনো পেন্ডিং ডিভাইস রিকোয়েস্ট নেই',
    'supportApplicationSubmitted': 'সাপোর্ট অ্যাপ্লিকেশন সাবমিট করা হয়েছে!',
    'reorderMainCategories': 'ক্যাটাগরি সাজান',
    'simulate': 'সিমুলেট',
    'noActiveChats': 'কোনো সক্রিয় চ্যাট নেই',
    'deliveryInProgress': 'ডেলিভারি চলছে',
    'emergency': 'জরুরী',
    'noData': 'কোনো তথ্য নেই',
    'selectDeliveryZone': 'ডেলিভারি জোন নির্বাচন করুন',
    'orderSubmittedSuccessfully': 'অর্ডার সফলভাবে সাবমিট করা হয়েছে',
    'categoryManagement': 'ক্যাটাগরি ম্যানেজমেন্ট',
    'assignDeliveryManHelper': 'ডেলিভারিম্যান / হেল্পার এসাইন করুন',
    'deleteItemQuery': 'আইটেমটি ডিলিট করতে চান?',
    'selectPaymentMethod': 'পেমেন্ট মেথড নির্বাচন করুন',
    'billTo': 'বিল টু:',
    'liveTracking': 'Live Tracking',
    'reject': 'প্রত্যাখ্যান',
    'selectParentMultiLevel': 'প্যারেন্ট সিলেক্ট করুন (মাল্টি-লেভেল)',
    'couponApplied': 'কুপন প্রয়োগ করা হয়েছে!',
    'changeDeliveryAddress': 'ডেলিভারি ঠিকানা পরিবর্তন করুন',
    'editUserRoleShops': 'ইউজার রোল ও শপ এডিট করুন',
    'newZone': 'নতুন জোন',
    'seedDemoDataPrevMonth': 'ডেমো ডাটা সিড (গত মাস)',
    'errorLoadingCoupons': 'কুপন লোড করতে সমস্যা হয়েছে',
    'staffCommissions': 'স্টাফ কমিশন',
    'deleteProductQuery': 'পণ্যটি ডিলিট করতে চান?',
    'noItemsFound': 'কোনো আইটেম পাওয়া যায়নি',
    'addExpense': 'খরচ যোগ করুন',
    'addNewStaff': 'নতুন স্টাফ যোগ করুন',
    'assignOrganizationalRole': 'প্রাতিষ্ঠানিক রোল এসাইন করুন',
    'deleteCategoryQuery': 'ক্যাটাগরি ডিলিট করতে চান?',
    'selectDistrict': 'জেলা নির্বাচন করুন',
    'selectUpazila': 'উপজেলা নির্বাচন করুন',
    'withPhone': 'মোাবাইল দিয়ে',
    'withEmail': 'ইমেইল দিয়ে',
    'alreadyHaveAccount': 'অ্যাকাউন্ট আছে?',
    'optional': 'ঐচ্ছিক',
    'fillRequiredFields': 'প্রয়োজনীয় তথ্য প্রদান করুন',
    'signupSuccess': 'নিবন্ধন সফল হয়েছে',
    'simulatingUser': 'ইউজার সিমুলেশন চলছে',
    'couldNotLaunchWhatsApp': 'হোয়াটসঅ্যাপ খোলা সম্ভব হচ্ছে না',
    'couldNotMakeCall': 'কল করা সম্ভব হচ্ছে না',
    'personalHub': 'পার্সোনাল হাব',
    'joinEarn': 'যুক্ত হোন ও আয় করুন',
    'supportHelp': 'সাপোর্ট ও সহায়তা',
    'informationHub': 'তথ্য হাব',
    'appSettings': 'অ্যাপ সেটিিংস',
    'light': 'লাইট',
    'dark': 'ডার্ক',
    'reseller': 'রিসেলার',
    'rider': 'রাইডার',
    'staff': 'স্টাফ',
    'faqs': 'সাধারণ জিজ্ঞাসা (FAQ)',
    'terms': 'শর্তাবলী',
    'about': 'আমাদের সম্পর্কে',
    'referEarn': 'রেফার করে ইনকাম করুন',
    'yourCode': 'আপনার কোড',
    'goodMorning': 'শুভ সকাল',
    'goodAfternoon': 'শুভ দুপুর',
    'goodEvening': 'শুভ সন্ধ্যা',
    'goodNight': 'শুভ রাত্রি',
    'motherLanguageDay': '২১শে ফেব্রুয়ারির শুভেচ্ছা',
    'independenceDay': 'স্বাধীনতা দিবসের শুভেচ্ছা',
    'victoryDay': 'বিজয় দিবসের শুভেচ্ছা',
    'shubhoNobobarsho': 'শুভ নববর্ষ!',
    'express': 'এক্সপ্রেস',
    'verified': 'ভেরিফাইড',
    'points': 'পয়েন্টস',
    'tapToViewDetails': 'বিস্তারিত দেখতে ট্যাপ করুন',
    'permissionsMissing': 'অনুমতি প্রয়োজন',
    'enableNow': 'এখনই দিন',
    'howToOrder': 'কিভাবে অর্ডার করবেন?',
    'howToOrderDesc': 'পণ্য বাছাই করুন, ব্যাগে যোগ করুন এবং চেকআউট সম্পন্ন করুন।',
    'whatAreRewards': 'রিওয়ার্ড পয়েন্ট কি?',
    'whatAreRewardsDesc': 'কেনাকাটা এবং রেফারের মাধ্যমে অর্জিত পয়েন্ট যা ডিসকাউন্ট হিসেবে ব্যবহার করা যায়।',
    'myOrders': 'আমার অর্ডারসমূহ',
    'myWishlist': 'আমার পছন্দের তালিকা',
    'myWallet': 'আমার ওয়ালেট',
    'district': 'জেলা',
    'upazila': 'উপজেলা',
    'shoppingBag': 'শপিং ব্যাগ',
    'orderMoreToUsePoints': 'পয়েন্ট ব্যবহার করতে আরও অর্ডার করুন',
    'itemsInCart': 'টি পণ্য',
    'save_label': 'সাশ্রয়',
    'onOrdersAbove_label': '৳ এর উপরে অর্ডারে',
    'noTopBuyers': 'এই মাসে কোনো সেরা ক্রেতা নেই',
    'megaDrawPool': 'মেগা ড্র পুল',
    'megaDrawPoolDesc': 'বিজয়ীদের পুল থেকে মেগা ড্রয়ের জন্য বিজয়ী নির্বাচন করা হবে।',
    'nextMegaDraw': 'পরবর্তী মেগা ড্র',
    'prize': 'পুরস্কার',
    'gold': 'স্বর্ণ',
    'bulkPricingTitle': 'প্যাকেজ মূল্য (Bulk Pricing)',
    'roleVendor': 'ভেন্ডর প্যানেল',
    'myInventory': 'আমার ইনভেন্টরি',
    'analytics': 'অ্যানালিটিক্স',
    'chatModerationWarning': 'নিরাপত্তার স্বার্থে ফোন নম্বর বা স্প্যাম লিংক শেয়ার করা নিষেধ।',
    'loginRequired': 'অর্ডার দেখতে লগইন করুন',
    'confirmDelivery': 'ডেলিভারি নিশ্চিত করুন',
    'confirmDeliveryDesc': 'আপনি কি পণ্যটি বুঝে পেয়েছেন? নিশ্চিত করলে ভেন্ডর পেমেন্ট পাবেন।',
    'confirm': 'নিশ্চিত করুন',
    'writeReview': 'রিভিউ লিখুন',
    'orderDeliveredDesc': 'অর্ডারটি সফলভাবে ডেলিভারি করা হয়েছে।',
    'orderTip': 'টিপস: অর্ডার প্রসেসিং হতে ১-৩ দিন সময় লাগতে পারে।',
    'noOrders': 'কোনো অর্ডার পাওয়া যায়নি',
    'myOrdersTitle': 'আমার অর্ডারসমূহ',
    'hubActionOrders': 'আমার অর্ডার',
    'hubActionWishlist': 'পছন্দের তালিকা',
    'hubActionWallet': 'আমার ওয়ালেট',
    'hubActionEdit': 'প্রোফাইল এডিট',
    'hubActionReseller': 'রিসেলার হোন',
    'hubActionRider': 'রাইডার হোন',
    'hubActionStaff': 'স্টাফ হোন',
    'teamPartners': 'পার্টনার ও টিম',
    'conversations': 'কথোপকথন',
    'messageHistory': 'মেসেজ হিস্ট্রি',
    'staffChatHistory': 'স্টাফ চ্যাট হিস্ট্রি',
    'signOut': 'লগআউট',
    'ptsAvailable': 'বর্তমান পয়েন্ট',
    'updating': 'আপডেট হচ্ছে...',
    'updateComplete': 'আপডেট সম্পন্ন',
    'yourInviteCode': 'আপনার ইনভাইট কোড',
    'copied': 'কপি হয়েছে',
    'adminControlPanel': 'অ্যাডমিন কন্ট্রোল প্যানেল',
    'craftedWith': 'Crafted with ❤️ by',
    'defaultDevName': 'Njel IT',
    'defaultDevUrl': 'https://njel.com.bd',
    'addToBagBtn': 'ব্যাগে যোগ করুন',
    'descriptionTitle': 'পণ্যের বিবরণ',
    'similarProducts': 'সদৃশ পণ্য',
    'noSimilarFound': 'কোনো সদৃশ পণ্য পাওয়া যায়নি',
    'trustAuthentic': '১০০% আসল পণ্য',
    'trustReturn': '৭ দিনের রিটার্ন',
    'trustFastDelivery': 'দ্রুত ডেলিভারি',
  };

  // --- English Translations ---
  static const Map<String, String> _english = {
    'appName': 'Paykari Bazar',
    'appNameAdmin': 'Paykari Bazar (Admin)',
    'rewardsRankings': 'Rewards & Rankings',
    'voucherCenter': 'Coupon & Vouchers',
    'topBuyersMonth': 'Top Buyers (This Month)',
    'topBuyersPerformance': 'Top Buyers Performance',
    'emergencyHeroesMonth': 'Medicine Heroes (This Month)',
    'bloodHeroesMonth': 'Blood Heroes (This Month)',
    'prevMonthWinners': 'Last Month Winners',
    'megaDrawWinners': 'Mega Draw Winners',
    'availableCoupons': 'Available Coupons',
    'emergencyMedicineBlood': 'Emergency Medicine & Blood',
    'riderDashboard': 'Rider Dashboard',
    'downloadHistory': 'Download Order History',
    'helpSupport': 'Help & Support',
    'joinPaykariBazar': 'Join Paykari Bazar',
    'account': 'Account',
    'pharmacy': 'Pharmacy',
    'bloodAid': 'Blood Aid',
    'bloodRequest': 'Blood Request',
    'helpline': 'Helpline',
    'home': 'Home',
    'offers': 'Offers',
    'rewards': 'Rewards',
    'profile': 'Profile',
    'emergencyService': 'Emergency Service',
    'noPurchasesMonth': 'No purchases this month yet',
    'noActiveHeroes': 'No heroes active this month',
    'noMegaDraws': 'No mega draws conducted yet',
    'noVouchersFound': 'No vouchers found',
    'noActiveCoupons': 'No active coupons at the moment',
    'cartEmpty': 'Your cart is empty',
    'noTasks': 'No tasks available',
    'noProductsFound': 'No products found',
    'noFavouritesYet': 'No favorites added yet',
    'exitAppTitle': 'Exit App?',
    'exitAppContent': 'Are you sure you want to exit the app?',
    'viewAll': 'View All',
    'flashDeals': 'Flash Deals',
    'newArrivals': 'New Arrivals',
    'justForYou': 'Just For You',
    'comboPack': 'Combo Pack',
    'quickReorder': 'Quick Reorder',
    'buyLastItems': 'Buy items from your last orders',
    'reorderBtn': 'Order',
    'searchHint': 'Search products...',
    'noFlashSales': 'No flash sales currently',
    'loading': 'Loading...',
    'pleaseWait': 'Please wait...',
    'adminDashboard': 'Admin Dashboard',
    'businessOverview': 'Business Overview',
    'totalOrders': 'Total Orders',
    'totalUsers': 'Total Users',
    'revenue': 'Revenue',
    'pending': 'Pending',
    'orderTrends': 'Order Trends',
    'topSellingProducts': 'Top Selling Products',
    'salesByCategory': 'Sales by Category',
    'viewFeedbacks': 'View Feedbacks',
    'alert': 'Alert',
    'newMessage': 'New Message',
    'cartReminderTitle': 'Items in Cart!',
    'cartReminderBody': 'Complete your order before your favorite items run out.',
    'emergencyOrderTitle': 'Emergency Order!',
    'emergencyOrderBody': 'An emergency order has arrived. Please take action immediately.',
    'priceDropTitle': 'Price Drop!',
    'priceDropBody': 'Price dropped for your favorite product!',
    'deliveryProximityTitle': 'Rider is Near!',
    'deliveryProximityBody': 'The rider is arriving shortly with your order.',
    'bloodNeeded': 'Blood Needed',
    'bloodNeededDesc': 'Blood Needed',
    'orderUpdateTitle': 'Order Update',
    'order_label': 'Order',
    'order': 'Order',
    'Pending': 'Pending',
    'Processing': 'Processing',
    'Shipped': 'Shipped',
    'Delivered': 'Delivered',
    'downloadInvoice': 'Download Invoice',
    'deliveryTasks': 'Delivery Tasks',
    'markAsDelivered': 'Mark as Delivered',
    'callCustomer': 'Call Customer',
    'navigation': 'Navigate',
    'noAssignedTasks': 'No tasks assigned to you',
    'staffLogin': 'Staff Login',
    'invalidStaff': 'This account is not registered as staff',
    'latestAdded': 'Latest Added',
    'nameAz': 'Name (A-Z)',
    'priceLowHigh': 'Price: Low to High',
    'priceHighLow': 'Price: High to Low',
    'priceRange': 'Price Range',
    'feedbackTitle': 'Share Your Feedback',
    'submitFeedback': 'Submit Feedback',
    'feedbackHint': 'Type here...',
    'thankYouFeedback': 'Thank you for your feedback!',
    'ratingRequired': 'Please provide a rating',
    'errorOccurred': 'An error occurred',
    'networkError': 'No internet connection. Please check.',
    'serverError': 'Server error. Please try again.',
    'unauthorized': 'Please login again.',
    'userNotFound': 'No account found with this email/phone',
    'wrongPassword': 'Wrong password. Try again.',
    'tooManyRequests': 'Blocked due to too many attempts. Try later.',
    'authError': 'Authentication failed',
    'tryAgain': 'Try Again',
    'emailAlreadyInUse': 'Email is already in use',
    'uploadFailed': 'Upload failed',
    'success': 'Success!',
    'updateSuccess': 'Updated successfully',
    'fillAllFields': 'Please fill all fields',
    'collectCoupons': 'Collect coupons for extra discounts',
    'copyCode': 'Code copied!',
    'reorderFastTrack': 'Fast-track your previous orders',
    'submitOrder': 'Submit Order',
    'logout': 'Logout',
    'login': 'Login',
    'signup': 'Signup',
    'cancel': 'Cancel',
    'yes': 'Yes',
    'no': 'No',
    'viewCart': 'View Cart',
    'add': 'Add',
    'buyNow': 'Buy Now: ',
    'startShopping': 'Start Shopping',
    'confirmOrder': 'Confirm Order',
    'saveChanges': 'Save Changes',
    'shareEarn': 'Share & Earn',
    'mobile': 'Mobile',
    'email': 'Email',
    'rememberMe': 'Remember Me',
    'forgotPassword': 'Forgot Password?',
    'orContinueWith': 'Or continue with',
    'noAccount': 'No account?',
    'myCurrentPoints': 'My Current Points',
    'redeemPointsHint': 'Get discount during checkout',
    'pts': 'Pts',
    'rewardEarned': 'Reward Earned! 🎁',
    'pointsEarnedMsg': 'Points Earned!',
    'loginTitle': 'Login',
    'signupTitle': 'Signup',
    'mobileNumber': 'Mobile Number',
    'password': 'Password',
    'fullName': 'Full Name',
    'emailAddress': 'Email Address',
    'referralCode': 'Referral Code (Optional)',
    'profileProgress': 'Profile Progress',
    'editProfile': 'Edit Profile',
    'changePassword': 'Change Password',
    'liveChat': 'Live Chat',
    'whatsappSupport': 'WhatsApp Support',
    'directCall': 'Direct Call',
    'howToUse': 'How to Use',
    'termsConditions': 'Terms & Conditions',
    'patientType': 'Patient Type',
    'bloodGroup': 'Blood Group',
    'bagsNeeded': 'Bags Needed',
    'hospitalArea': 'Hospital or Area',
    'contactNumber': 'Contact Number',
    'bloodRequestAlert': 'Emergency blood request will be sent to nearby donors.',
    'medicineDetails': 'Medicine Details / Instructions',
    'attachPrescription': 'Attach Prescription',
    'medicineNamesHint': 'Enter medicine names and quantity...',
    'child': 'Child',
    'youth': 'Youth',
    'elderly': 'Elderly',
    'pregnantMother': 'Pregnant Mother',
    'seriouslyIll': 'Seriously Ill',
    'criticallyInjured': 'Critically Injured',
    'applyForSupportTeam': 'Apply for Support Team',
    'orderPlacedSuccess': 'Order placed successfully',
    'titleMessageRequired': 'Title and message are required',
    'locationAdded': 'Location added',
    'noPendingDeviceRequests': 'No pending device requests',
    'supportApplicationSubmitted': 'Support application submitted!',
    'reorderMainCategories': 'Reorder Categories',
    'simulate': 'Simulate',
    'noActiveChats': 'No active chats',
    'deliveryInProgress': 'Delivery in Progress',
    'emergency': 'Emergency',
    'noData': 'No data available',
    'selectDeliveryZone': 'Select Delivery Zone',
    'orderSubmittedSuccessfully': 'Order submitted successfully',
    'categoryManagement': 'Category Management',
    'assignDeliveryManHelper': 'Assign Delivery Man / Helper',
    'deleteItemQuery': 'Delete this item?',
    'selectPaymentMethod': 'Select Payment Method',
    'billTo': 'Bill To:',
    'liveTracking': 'Live Tracking',
    'reject': 'Reject',
    'selectParentMultiLevel': 'Select Parent (Multi-level)',
    'couponApplied': 'Coupon Applied!',
    'changeDeliveryAddress': 'Change Delivery Address',
    'editUserRoleShops': 'Edit User Role & Shops',
    'newZone': 'New Zone',
    'seedDemoDataPrevMonth': 'Seed Demo Data (Last Month)',
    'errorLoadingCoupons': 'Error loading coupons',
    'staffCommissions': 'Staff Commissions',
    'deleteProductQuery': 'Delete this product?',
    'noItemsFound': 'No items found',
    'addExpense': 'Add Expense',
    'addNewStaff': 'Add New Staff',
    'assignOrganizationalRole': 'Assign Organizational Role',
    'deleteCategoryQuery': 'Delete this category?',
    'selectDistrict': 'Select District',
    'selectUpazila': 'Select Upazila',
    'withPhone': 'With Mobile',
    'withEmail': 'With Email',
    'alreadyHaveAccount': 'Already have account?',
    'optional': 'Optional',
    'fillRequiredFields': 'Fill required fields',
    'signupSuccess': 'Signup Successful',
    'simulatingUser': 'User Simulation Active',
    'couldNotLaunchWhatsApp': 'Could not launch WhatsApp',
    'couldNotMakeCall': 'Could not make call',
    'personalHub': 'Personal Hub',
    'joinEarn': 'Join & Earn',
    'supportHelp': 'Support & Help',
    'informationHub': 'Information Hub',
    'appSettings': 'App Settings',
    'light': 'Light',
    'dark': 'Dark',
    'reseller': 'Reseller',
    'rider': 'Rider',
    'staff': 'Staff',
    'faqs': 'FAQs',
    'terms': 'Terms',
    'about': 'About Us',
    'referEarn': 'Refer & Earn',
    'yourCode': 'Your Code',
    'goodMorning': 'Good Morning',
    'goodAfternoon': 'Good Afternoon',
    'goodEvening': 'Good Evening',
    'goodNight': 'Good Night',
    'motherLanguageDay': 'Happy Mother Language Day',
    'independenceDay': 'Happy Independence Day',
    'victoryDay': 'Happy Victory Day',
    'shubhoNobobarsho': 'Shubho Nobobarsho!',
    'express': 'Express',
    'verified': 'Verified',
    'points': 'Points',
    'tapToViewDetails': 'Tap to view details',
    'permissionsMissing': 'Permissions Missing',
    'enableNow': 'Enable Now',
    'howToOrder': 'How to Order?',
    'howToOrderDesc': 'Select products, add to bag, and checkout.',
    'whatAreRewards': 'What are rewards?',
    'whatAreRewardsDesc': 'Points earned through purchases and referrals used for discounts.',
    'myOrders': 'My Orders',
    'myWishlist': 'My Wishlist',
    'myWallet': 'My Wallet',
    'district': 'District',
    'upazila': 'Upazila',
    'shoppingBag': 'Shopping Bag',
    'orderMoreToUsePoints': 'Order more to use points',
    'itemsInCart': 'Items',
    'save_label': 'Save',
    'onOrdersAbove_label': 'on orders above ৳',
    'noTopBuyers': 'No top buyers this month',
    'megaDrawPool': 'Mega Draw Pool',
    'megaDrawPoolDesc': 'Winners will be selected from this pool for the Mega Draw.',
    'nextMegaDraw': 'Next Mega Draw',
    'prize': 'Prize',
    'gold': 'Gold',
    'bulkPricingTitle': 'Bulk Pricing',
    'roleVendor': 'Vendor Panel',
    'myInventory': 'My Inventory',
    'analytics': 'Analytics',
    'chatModerationWarning': 'For security, sharing phone numbers or spam links is prohibited.',
    'loginRequired': 'Login to view orders',
    'confirmDelivery': 'Confirm Delivery',
    'confirmDeliveryDesc': 'Have you received the product? Once confirmed, vendor will receive payment.',
    'confirm': 'Confirm',
    'writeReview': 'Write Review',
    'orderDeliveredDesc': 'Order has been successfully delivered.',
    'orderTip': 'Tip: Order processing may take 1-3 days.',
    'noOrders': 'No orders found',
    'myOrdersTitle': 'My Orders',
    'hubActionOrders': 'My Orders',
    'hubActionWishlist': 'Wishlist',
    'hubActionWallet': 'My Wallet',
    'hubActionEdit': 'Edit Profile',
    'hubActionReseller': 'Become Reseller',
    'hubActionRider': 'Become Rider',
    'hubActionStaff': 'Become Staff',
    'teamPartners': 'Partners & Team',
    'conversations': 'Conversations',
    'messageHistory': 'Message History',
    'staffChatHistory': 'Staff Chat History',
    'signOut': 'Sign Out',
    'ptsAvailable': 'Points Available',
    'updating': 'Updating...',
    'updateComplete': 'Update Complete',
    'yourInviteCode': 'Your Invite Code',
    'copied': 'Copied',
    'adminControlPanel': 'Admin Control Panel',
    'craftedWith': 'Crafted with ❤️ by',
    'defaultDevName': 'Njel IT',
    'defaultDevUrl': 'https://njel.com.bd',
    'addToBagBtn': 'Add to Bag',
    'descriptionTitle': 'Product Description',
    'similarProducts': 'Similar Products',
    'noSimilarFound': 'No similar products found',
    'trustAuthentic': '100% Authentic',
    'trustReturn': '7 Days Return',
    'trustFastDelivery': 'Fast Delivery',
  };
}
